version: '3.8'

services:
  tv-organizer:
    image: ghcr.io/verncat/jellyfin-ai-series-organizer:latest
    container_name: tv-series-organizer
    ports:
      - "9002:9002"
    volumes:
      - /mnt/toshiba/nextcloud/vern/files/Downloads/tv:/app/tv
      - /mnt/toshiba/nextcloud/vern/files/Downloads/tv_unordered:/app/tv_unordered
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    restart: unless-stopped
